services:
  pds:
    image: harrybrwn/pds:latest
    build:
      context: .
    volumes:
      - pds-data:/pds
    environment:
      PDS_PORT: '3000'
      PDS_HOSTNAME: 'pds.lab'
      PDS_ADMIN_PASSWORD: 'testlab0'
      PDS_DATA_DIRECTORY: /pds
      PDS_BLOBSTORE_DISK_LOCATION: /pds/blobs
      PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX: '80b91c26ebe587157e049e1c724b3744fe767ea52d1e7a61e455eb955f18d19e'
      PDS_JWT_SECRET: 'bf5cee2342fa4f950b1ddda6414aa118'
      PDS_BLOB_UPLOAD_LIMIT: '52428800'
      # PDS_BSKY_APP_VIEW_URL: https://api.bsky.app
      # PDS_BSKY_APP_VIEW_DID: did:web:api.bsky.app
      # PDS_REPORT_SERVICE_URL: https://mod.bsky.app
      # PDS_REPORT_SERVICE_DID: did:plc:ar7c4by46qjdydhdevvrndac
      # PDS_CRAWLERS: https://bsky.network
    networks:
      default:
        aliases:
          # - pds.bluesky.svc.cluster.local
          - pds.lab

  pdsadmin:
    image: harrybrwn/curl:3.20
    entrypoint: pdsadmin
    volumes:
      - ./scripts/pdsadmin.sh:/usr/bin/pdsadmin:ro
    environment:
      PDSADMIN_SCHEME: 'http'
      PDS_HOSTNAME: 'pds.lab:3000'
      PDS_ADMIN_PASSWORD: 'testlab0'

volumes:
  pds-data:

# networks:
#   bsky:
