commonLabels:
  environment: prd

resources:
  - ../../system/prometheus
  - ../../system/secrets
  - ../../system/cert-manager
  - ../../system/reloader
  - ../../system/replicator
  - ../../system/traefik
  - ../../system/traefik-extras
  - ../../system/wordpress-operator
  - ../../system/mariadb-operator
  - ../../common/storage/nfs
  - cert-manager-values.yml
  - prometheus-resources.yml
  - mariadb-operator-extras.yml
  - reloader-extras.yml
  - replicator-extras.yml

patches:
  - target:
      kind: Deployment
      name: nfs-client-provisioner
    path: nfs-provisioner.yml

secretGenerator: []
  # # Provides:
  # # AWS_ACCESS_KEY_ID=...
  # # AWS_SECRET_ACCESS_KEY=...
  # # AWS_ENDPOINTS=https://<...>.r2.cloudflarestorage.com
  # - name: longhorn-r2-backup
  #   namespace: longhorn-system
  #   envs: [env/longhorn-backup.env]
  #   options: { disableNameSuffixHash: true }
